algo = input('Digite algo para análise: ')
print('O tipo primitivo disso é: {}'.format(type(algo)))
print('Só tem espaço? > {}'.format(algo.isspace()))
print('É alfanumérico? > {}'.format(algo.isalnum()))
print('É totalmente alfabético? > {}'.format(algo.isalpha()))
print('É totalmente numérico? > {}'.format(algo.isnumeric()))
print('É totalmente MAIÚSCULO? > {}'.format(algo.isupper()))
print('É totalmente minúsculo? > {}'.format(algo.islower()))
print('Está Capitalizado? > {}'.format(algo.istitle()))
