algo = input('Digite algo para análise: ')
print('O tipo primitivo disso é: \033[4m{}\033[m'.format(type(algo)))
print('Só tem espaço? > \033[4m{}\033[m'.format(algo.isspace()))
print('É alfanumérico? > \033[7;32;46m{}\033[m'.format(algo.isalnum()))
print('É totalmente alfabético? > \033[7;37;42m{}\033[m'.format(algo.isalpha()))
print('É totalmente numérico? > \033[1;34;45m{}\033[m'.format(algo.isnumeric()))
print('É totalmente MAIÚSCULO? > {}'.format(algo.isupper()))
print('É totalmente minúsculo? > {}'.format(algo.islower()))
print('Está Capitalizado? > {}'.format(algo.istitle()))
